name: Test

on:
  - push
  - pull_request
  - pull_request_target

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test with Symfony ${{ matrix.symfony-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony-version: ['^4', '^5', '^6']
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"

      - name: Install symfony/http-foundation
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          command: require
          args: symfony/http-foundation:${{ matrix.symfony-version }}

      - name: Lint
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          command: run-script
          args: analyze

      - name: Test
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          command: run-script
          args: test
