name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint_test:
    name: Lint & Test
    runs-on: nixos
    strategy:
      matrix:
        reqs:
          - symfony: "^5"
            shell: "php81"
          - symfony: "^5"
            shell: "php82"
          - symfony: "^5"
            shell: "php83"
          - symfony: "^6"
            shell: "php81"
          - symfony: "^6"
            shell: "php82"
          - symfony: "^6"
            shell: "php83"
          - symfony: "^7"
            shell: "php82"
          - symfony: "^7"
            shell: "php83"
          - symfony: "^6"
            shell: "php84"
          - symfony: "^7"
            shell: "php84"
    defaults:
      run:
        shell: nix develop .#${{ matrix.reqs.shell }} --command bash {0}
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: >-
          composer update --no-ansi --no-interaction --no-progress &&
          composer require symfony/http-foundation:${{ matrix.reqs.symfony }}

      - name: PHPCS
        run: ./vendor/bin/phpcs -s .

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse --level 8 src tests

      - name: PHPUnit
        run: ./vendor/bin/phpunit tests
